name: Test Job

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: rahul
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name : copying index.html
      run:  |
        cp index.html /home/manish
        cd /home/manish && mkdir test
        cp index.html /home/manish/test